name: Check examples

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check_examples:
    name: Check analyzers for examples
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.9, 3.13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - name: Set up Python
        uses: ni/python-actions/setup-python@f42e2f27a585f5d47efcab79b608ec0ec97191c9 # v0.6.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@f42e2f27a585f5d47efcab79b608ec0ec97191c9 # v0.6.1
      - name: Install dependencies
        run: poetry install --with=dev,lint
      - name: Check examples formatting
        run: poetry run black --check examples/
      - name: Type check examples
        run: poetry run mypy examples/