name: Check docs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check_docs:
    name: Check docs for {{package_full_name}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - name: Set up Python
        uses: ni/python-actions/setup-python@f42e2f27a585f5d47efcab79b608ec0ec97191c9 # v0.6.1
        with:
          python-version: 3.13
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@f42e2f27a585f5d47efcab79b608ec0ec97191c9 # v0.6.1
      - name: Install dependencies
        run: poetry install --with=docs
      - name: Build documentation
        run: |
          cd docs
          poetry run sphinx-build -b html . _build/html -W