name: Run unit tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      python-version:
        required: true
        type: string
        default: "3.13"
      os:
        required: true
        type: string
        default: "ubuntu-latest"

jobs:
  run_unit_tests:
    name: Run unit tests (Python ${{ inputs.python-version }}, ${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - name: Set up Python
        uses: ni/python-actions/setup-python@f42e2f27a585f5d47efcab79b608ec0ec97191c9 # v0.6.1
        with:
          python-version: ${{ inputs.python-version }}
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@f42e2f27a585f5d47efcab79b608ec0ec97191c9 # v0.6.1
      - name: Install dependencies
        run: poetry install --with=test
      - name: Run unit tests
        run: poetry run pytest tests/ --cov={{package_namespace}}.{{package_name}} --cov-report=xml --cov-report=html
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'